name: Run Backend CI

on:
  push:
    branches:
      - develop
    paths:
      - "backend/**"
  pull_request:
    branches:
      - develop
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository in Virtual Machine
        uses: actions/checkout@v4
      - name: Install Dependencies
        working-directory: backend
        run: |
          npm install
      - name: Run Tests
        working-directory: backend
        run: |
          npm test

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: backend/Dockerfile
