name: Run Backend CI

on:
  push:
    branches:
      - develop
    paths:
      - "backend/**"
  pull_request:
    branches:
      - develop
    paths:
      - "backend/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository in Virtual Machine
        uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: backend
        run: |
          npm install
      - name: Run Tests
        working-directory: backend
        run: |
          npm test