name: Run Mobile CI

on:
  push:
    branches:
      - develop
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - develop
    paths:
      - "frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository in Virtual Machine
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: frontend/iQMA-Skills-Builder
        run: |
          npm install

      - name: Run Tests
        working-directory: frontend/iQMA-Skills-Builder
        run: |
          npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter@v7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
