name: Run Mobile CI

on:
  push:
    branches:
      - develop
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - develop
    paths:
      - "frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositroy in Virtual Machine
        uses: actions/checkout@v2
      - name: Install Dependecies
        working-directory: frontend
        run: |
          npm install
      - name: Run Tests
        working-directory: frontend
        run: |
          npm install

      

  
      